version: '2'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb/:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=ftlig
      - INFLUXDB_ADMIN_USER=admin	
      - INFLUXDB_ADMIN_PASSWORD=adm!nIstrator
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - ./chronograf/:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://dockerserver:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=adm!nIstrator
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin	
      - GF_SECURITY_ADMIN_PASSWORD=adm!nIstrator
      - GF_SERVER_ROOT_URL=http://dockerserver
      - GF_DEFAULT_INSTANCE_NAME=dockerserver
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_ENABLE_GZIP=true
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ROLE=Admin
